
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-hairydynamicist}"
    image: cybulde-data-processing
    platform: linux/amd64
    container_name: cybulde-data-processing-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-jmurray}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-jmurray}/.config/gcloud
    ports:
      - 8888:8888

    ipc: host
    init: true


