infrastructure:
  project_id: cybuldeproject
  zone: europe-west4-a
  network: default
data_parquet_path: gs://jmcybulde/data/processed/default_run/dev.parquet
text_column_name: cleaned_text
docker_image_name: europe-west4-docker.pkg.dev/cybuldeproject/cybulde/cybulde-data-processing
docker_image_tag: 6e165546-6da2-4801-bb09-61b2332d5f23
